# Generated by Django 6.1 on 2026-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration',
            name='utr_number',
            field=models.CharField(default='PENDING_UTR', max_length=50),
        ),
    ]
