# Generated by Django 6.1 on 2026-08-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_memberregistration_utr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
